Web/Web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^product/', include('product.urls', namespace='product')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^main/', include('main.urls', namespace='main')),    
    url(r'^.*', include('main.urls')),
]

Web/main/urls.py
from django.conf.urls import url
from main import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^mainProduct/(?P<productId>[0-9]+)/$', views.mainProduct, name='mainProduct'),
    url(r'^mainProduct2/(?P<productId>[0-9]+)/$', views.mainProduct2, name='mainProduct2'),
]

Web/product/urls.py
from django.conf.urls import url
from product import views


urlpatterns = [
    url(r'^$', views.product, name='product'),
]

Web/shop/urls.py
from django.conf.urls import url
from shop import views


urlpatterns = [
    url(r'^$', views.shop, name='shop'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^order/$', views.order, name='order'),
    url(r'^shopDelete/(?P<shopId>[0-9]+)/$', views.shopDelete, name='shopDelete'),
    url(r'^fin/$', views.fin, name='fin'),
    url(r'^fin2/$', views.fin2, name='fin2'),
]

Web/main/models.py
from django.db import models

Web/product/models.py
from django.db import models



class Product(models.Model):
    #產品資料
    name = models.CharField(max_length=128, unique=True)#產品名稱
    ename = models.CharField(max_length=128, unique=True)#產品英文名稱
    price = models.IntegerField()#產品價格
    title = models.CharField(max_length=128, unique=True)#產品標題
    Introduction = models.TextField()#產品簡介
    productimg = models.ImageField(height_field=500
                                   , width_field=500, max_length=100)#產品圖片
    titleimg = models.ImageField(height_field=375
                                   , width_field=372, max_length=100)#標題圖片
    #品飲紀錄
    colour = models.CharField(max_length=128, unique=True)#色澤
    smell = models.TextField()#嗅覺
    taste = models.TextField()#口感
    After = models.CharField(max_length=128, unique=True)#餘韻
    cask = models.TextField()#橡木桶資訊
    def __str__(self):
        return self.name
    
    
class Shop(models.Model):
    #購物車資料
    name = models.CharField(max_length=128, unique=True)#產品名稱
    price = models.IntegerField()#產品價格
    amount = models.IntegerField()#數量
    def __str__(self):
        return self.name
    
    
    

    
    
    
    
    

Web/shop/models.py
from django.db import models

# Create your models here.

Web/main/views.py
from django.shortcuts import render, get_object_or_404, redirect

from product.models import Product,Shop
from django.contrib import messages


def main(request):
    products = Product.objects.all()
    context = {'products':products}
    return render(request, 'main/main.html',context)



def mainProduct(request, productId):
    product = get_object_or_404(Product, id=productId)
    products = Product.objects.all()
    context = {'products':products,'product':product}
    return render(request, 'main/mainProduct.html',context)
    



def mainProduct2(request, productId):
    product = get_object_or_404(Product, id=productId)
    products = Product.objects.all()
    context = {'products':products,'product':product}
    amount = int(request.GET.get('amount'))
    shop = Shop()
    shop.name = product.name
    shop.price = product.price
    shop.amount = amount
    shop.save()
    messages.success(request, '產品已加入購物車。')
    return render(request, 'main/mainProduct.html',context)
    

Web/product/views.py
from django.shortcuts import render, redirect

from product.models import Product

# Create your views here.


def product(request):
    '''
    Create a new article instance
        1. If method is GET, render an empty form
        2. If method is POST, perform form validation and display error messages if the form is invalid
        3. Save the form to the model and redirect the user to the article page
    '''
    # TODO: finish the code
    products = Product.objects.all()
    context = {'products':products}
    template = 'product/product.html'
    if request.method == 'GET':
        return render(request,template,context)
    # POST
    name = request.POST.get('name')
    ename = request.POST.get('ename')
    price = int(request.POST.get('price'))
    title = request.POST.get('title')
    Introduction = request.POST.get('Introduction')
    colour = request.POST.get('colour')
    smell = request.POST.get('smell')
    taste = request.POST.get('taste')
    After = request.POST.get('After')
    cask = request.POST.get('cask')
    
    product = Product()
    product.name=name
    product.ename=ename
    product.price=price
    product.title=title
    product.Introduction=Introduction
    product.colour=colour
    product.smell=smell
    product.taste=taste
    product.After=After
    product.cask=cask
    product.save()
    return redirect('main:main')

Web/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404

from product.models import Product
from product.models import Shop


# Create your views here.

def shop(request):
    products = Product.objects.all()
    shops = Shop.objects.all()
    sub1 = 0
    sub = 0
    for x in shops:
        a=x.price * x.amount
        sub1+=a
        print(a)
    sub2=sub1+60
    
    context = {'products':products,'shops':shops,
               'sub':sub,'sub1':sub1,'sub2':sub2}
    return render(request, 'shop/shop.html',context)



def checkout(request):
    Delivery = request.GET.get('Delivery')
    payment = request.GET.get('payment')
    products = Product.objects.all()
    shops = Shop.objects.all()
    sub1 = 0
    sub = 0
    for x in shops:
        a=x.price * x.amount
        sub1+=a
        print(a)
    sub2=sub1+60
    context = {'products':products,'shops':shops,
               'payment':payment,'Delivery':Delivery,
               'sub':sub,'sub1':sub1,'sub2':sub2}
    return render(request, 'shop/checkout.html',context)



def order(request):
    name = request.GET.get('name')
    phone = request.GET.get('phone')
    address = request.GET.get('address')
    remark = request.GET.get('remark')
    Delivery = request.GET.get('Delivery')
    payment = request.GET.get('payment')
    products = Product.objects.all()
    shops = Shop.objects.all()
    sub1 = 0
    sub = 0
    for x in shops:
        a=x.price * x.amount
        sub1+=a
        print(a)
    sub2=sub1+60
    context = {'products':products,'shops':shops,'name':name
               ,'phone':phone,'address':address,'remark':remark
               ,'Delivery':Delivery,'payment':payment,
               'sub':sub,'sub1':sub1,'sub2':sub2}
    return render(request, 'shop/order.html',context)



def shopDelete(request, shopId):
    if request.method == 'GET':
        return shop(request)
    # POST
    shopToDelete = get_object_or_404(Shop, id=shopId)
    shopToDelete.delete()
    return redirect('shop:shop')



def fin(request):
    if request.method == 'GET':
        return order(request)
    # POST
    shops = Shop.objects.all()
    for x in shops:
        x.delete()
    return redirect('shop:fin2')



def fin2(request):
    products = Product.objects.all()
    context = {'products':products }
    return render(request, 'shop/fin.html',context)

Web/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>格蘭哥尼販賣小舖</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    
  <div id = "d3">
    <p id = "p1"><i>充滿著顯著又複雜的風味</i></p>
    <p id = "p2">格蘭哥尼 10 年雪莉桶威士忌的巴西堅果香和軟橡木的香氣；<br>
      格蘭哥尼 18 年雪莉新桶威士忌那極好的平衡；<br>
      或又是那擁有獨特的聖誕節蛋糕香味的格蘭哥尼 21 年雪莉桶威士忌 。<br>
      格蘭哥尼威士忌系列充滿著顯著又複雜的風味。
    </p>
    <br>
    <hr>
    <hr>
  </div>
  
  <div id = "d4">
    <ul>
     {% for product in products %}
        <li>
          <a class="a1" href="{% url 'main:mainProduct' product.id %}" >
          {% with 'main/img/'|add:product.ename|add:'.jpg' as staticImage %}
            <img src="{% static staticImage %}"  alt="GLEN"></a>
          {% endwith %}
        </li>
      {% endfor %}
      <div style="clear: both;"></div>
    </ul>
    <br>
    
    <div id = "d5">
    <table>
      <tr>
        <td id="td1">"我每晚都能安穩地入睡，因為我們長久以來，一直都是採用<br>
          和老祖宗相同的方法在打造世界級的威士忌。"</td>
        <td id="td2" rowspan="2">
        <img src="{% static 'main/img/GLENX1.png' %}" alt="GLEN"></td>
      </tr>
      <tr>
        <td id="td3">Robbie Hughes<br>酒廠經理</td>
      </tr>
     </table>
     <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
     
    </div>
    
  </div>
  </body>
</html>

Web/main/templates/main/mainProduct.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>{{ product.name }}</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/mainProduct.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    
    <div id = "d3">
      <p id = "p1"><i>{{ product.title }}</i></p>
      {{ product.Introduction|linebreaks }}
      <br>
      <hr>
    </div>
    
    <div id= "d4">
      <div id="dimg">
        {% with 'main/img/'|add:product.ename|add:'.png' as staticImage %}
        <img id="dimg" src="{% static staticImage %}"  alt="GLEN"></a>
        {% endwith %}
      </div>
      <table id = "tab1">
        <tr class = "tr1">
          <td id="td1"  colspan="2">品飲紀錄</td>
        </tr>
        <tr class = "tr2">
          <td class="td1">色澤</td>
          <td class="td2">{{ product.colour }}</td>
        </tr>
        <tr class = "tr1">
          <td class="td1">嗅覺</td>
          <td class="td2">{{ product.smell }}</td>
        </tr>
        <tr class = "tr2">
          <td class="td1">口感</td>
          <td class="td2">{{ product.taste }}</td>
        </tr>
        <tr class = "tr1">
          <td class="td1">餘韻</td>
          <td class="td2">{{ product.After }}</td>
        </tr>
        <tr class = "tr2">
          <td class="td1">威士忌橡木桶資訊</td>
          <td class="td2">{{ product.cask|linebreaks }}</td>
        </tr>
       </table>
       
      <div id="dd">
        <p id="p1">{{ product.name }}</p>
        
        <P id="p2">NT${{ product.price }}</P>
        <form method="get" action="{% url 'main:mainProduct2' product.id %}">
          {% csrf_token %}
          <p id="p3">數量</p>
          <input id="amount" type="number" name=amount>
          <br><br>
          <input class="btn" id="btn" type="submit" value="加入購物車">
          {% for message in messages %}
            <p class="{{ message.tags }}">{{ message }}</p>
         {% endfor %}
        </form>
      </div>
      <div style="clear: both;"></div>
      <hr>
      
      <div id = "d5">
      <br>
      <table>
        <tr>
          <td id="td1">"地利人和造就了這卓越的威士忌！"
          <td id="td2" rowspan="2">
          <img src="../../../static/main/img/GLENX1.png" alt="GLEN"></td>
        </tr>
        <tr>
          <td id="td3">Stephanie McIntyre<br>酒窖管理員</td>
        </tr>
       </table><br><br>
      </div>
    </div>
  </body>
</html>

Web/main/templates/main/menu.html
{% load staticfiles %}
<div id = "d1">
    <ul>
      <li id = "l1"><a href="{% url 'main:main' %}" id="a1">
      <img src="{% static 'main/img/GLEN.jpg' %}" id=img0 alt="GLEN"></a></li>
      <li id = "l2"><a href="{% url 'main:main' %}" id="a2">格蘭哥尼販賣小舖</a></li>
      <li id = "l3"><a href="{% url 'product:product' %}" id="a4">新增產品</a><br>
      <a href="{% url 'shop:shop' %}" id="a3">購物車/結帳</a></li>
    <div style="clear: both;"></div>
    </ul>
    <div style="clear: both;"></div>
  </div>
  
  <div id = "d2">
    <ul>
      <li id="l0"></li>
      {% for product in products %}
        <li><a href="{% url 'main:mainProduct' product.id %}">{{product.name}}</a></li>
      {% endfor %}
      <div style="clear: both;"></div>
    </ul>
  </div> 

Web/main/templates/main/messages.html
{% for message in messages %}
  <p class="{{ message.tags }}">{{ message }}</p>
{% endfor %}

Web/product/templates/product/product.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>新增產品</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/product.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <div id="d4">
    <p id="pp">新增產品</p>
    
      <table id="tb2">
        <tr class="tr11">
          <td>產品資料</td>
        </tr>
        <tr class="tr22">
        <form method="post" action="{% url 'product:product' %}" enctype="multipart/form-data">
         {% csrf_token %}
         <td>
         <p>名稱</p>
         <input id="name" type="text" name=name>
         <p>英文名稱</p>
         <input id="ename" type="text" name=ename>
         <p>價格</p>
         <input id="price" type="number" name=price>
         <p>標題</p>
         <input id="title" type="text" name=title>
         <p>簡介</p>
         <textarea id="Introduction"  name=Introduction></textarea>
         <p>產品圖像</p>
         <input type="file" name="productimg" id="productimg" >
         <p>標題圖像</p>
         <input type="file" name="titleimg" id="titleimg" >
         </td>
        </tr>
      </table>
      
      <table id="tb3">
        <tr class="tr11">
          <td>品飲紀錄</td>
        </tr>
        <tr class="tr22">
        <td>
        <p>色澤</p>
         <input id="colour" type="text" name=colour>
         <p>嗅覺</p>
         <textarea id="smell"  name=smell></textarea>
         <p>口感</p>
         <textarea id="taste"  name=taste></textarea>
         <p>餘韻</p>
         <input id="After" type="text" name=After>
         <p>橡木桶資訊</p>
         <textarea id="cask"  name=cask></textarea>
         <br><br><br><br>
        </td>
        </tr>
      </table>
      <br><br>
      <input class="btn" type="submit" value="新增">
      </form>
      <br><br><br><br><br><br>
      <br><br><br><br><br><br>
    </div>
    
  </body>
</html>

Web/shop/templates/shop/checkout.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>結帳</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/checkout.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <div id="d4">
      <br>
        <img id="shop" src="{% static 'main/img/shop1.png' %}"  alt="shop">
      <br>
      
      <table id="tab1">
        <tr class="tr1">
          <td colspan="4">購物車</td>
        <tr>
        <tr class="tr2">
          <td>商品資料</td>
          <td>單件價格</td>
          <td>數量</td>
          <td>小計</td>
        </tr>
        {% for shop in shops %}
          <tr class="tr3">
            <td>{{shop.name}}</td>
            <td>NT${{shop.price}}</td>
            <td>{{shop.amount}}</td>
            <td>NT${%  widthratio shop.price 1 shop.amount %}</td>
          </tr>
        {% endfor %}
      </table>
      
      <br><hr><br>
      
      <table id="tab2" class="tab2">
        <tr class="tr11">
          <td>顧客資料</td>
        </tr>
        <tr class="tr22">
          <td>
          <p>顧客名稱</p>
          <input type="text" name=name>
          <p>電子信箱</p>
          <input type="email" name=name>
          <p>電話號碼</p>
          <input type="mobile" name=name>
          <p>生日</p>
          <input type="date" name=name>
          <p>性別</p>
          <select id="sex" name="sex">
                    <option value="M">男</option>
                    <option value="G">女</option>
          </select>
          </td>
        </tr>
      </table>
      
      <table id="tab3" class="tab2">
        <tr class="tr11">
          <td>送貨資料 (運費:NT$60)</td>
        </tr>
        <tr class="tr22">
          <td id="td2">
          <form method="get" action="{% url 'shop:order' %}">
            已選擇送貨方式：
              {{ Delivery }}
              <input type="hidden" name="Delivery" value={{ Delivery }}>
            
              {% csrf_token %}
              <p>收件人名稱</p>
              <input type="text" name="name">
              <p id="p1">請填入收件人真實姓名，以確保順利收件。</p>
              <p>收件人電話號碼</p>
              <input type="text" name="phone">
              <p>地址</p>
              <input type="text" name="address">
            <br><br><br><br><br>
          </td>
          
        </tr>
      </table>
      
      <br><br>
      
      <table id="tab4" class="tab2">
        <tr class="tr11">
          <td>訂單備註</td>
        </tr>
        <tr class="tr22">
          <td>
          <textarea rows=7 cols=20 name="remark"></textarea>
          </td>
        </tr>
      </table>
      
      <table id="tab5" class="tab2">
        <tr class="tr11">
          <td>付款資料</td>
        </tr>
        <tr class="tr22">
          <td>
          <strong>合計:NT${{ sub2 }}</strong>
          <p>已選擇付款方式：
            {{ payment }}
            <input type="hidden" name="payment" value={{ payment }}>
          </p>
          <br><br>
          </td>
        </tr>
      </table>
      
      <br><br>
      
      <div id="dd5">
      <table>
      <tr>
      <td id="td1">
        <a class="btn" href="{% url 'shop:shop' %}" >回購物車</a>
      </td>
      <td id="td2">
        <input class="btn" type="submit" value="提交訂單">
        </form>
      </td>
      </tr>
      </table>
        
        
      </div>
      
    </div>
    
    <br>
    
  </body>
</html>

Web/shop/templates/shop/fin.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>結帳完成</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/fin.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <div id="d33">
    <p id="p1">您的訂單已確定提交，</p>
    <p id="p2">我們將盡快為您處裡訂單。</p>
    </div>
    <div id = "d55">
    
    <br><br><br><br><br>
    
    <table>
      <tr>
        <td id="td1">"格蘭哥尼那天然的深赤褐色、紅銅色和淺淺的金黃色，<br>
        是歲月和雪莉桶給我們最大的回報。"</td>
        <td id="td2" rowspan="2">
        <img src="{% static 'main/img/GLENX1.png' %}" alt="GLEN"></td>
      </tr>
      <tr>
        <td id="td3">JOHN GLASS<br>首席調酒師</td>
      </tr>
     </table>
     <br><br><br><br><br><br><br><br>
     <a class="btn" href="{% url 'main:main' %}">返回購物頁面</a>
     <br><br><br><br><br><br><br><br><br><br><br>
    </div>
  </body>
</html>

Web/shop/templates/shop/order.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>確認訂單</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/order.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <div id="d4">
      <br>
        <img id="shop" src="{% static 'main/img/shop2.png' %}"  alt="shop">
      <br>
      
      <table id="tab1">
        <tr class="tr1">
          <td colspan="4">購物車</td>
        <tr>
        <tr class="tr2">
          <td>商品資料</td>
          <td>單件價格</td>
          <td>數量</td>
          <td>小計</td>
        </tr>
        {% for shop in shops %}
          <tr class="tr3">
            <td>{{shop.name}}</td>
            <td>NT${{shop.price}}</td>
            <td>{{shop.amount}}</td>
            <td>NT${%  widthratio shop.price 1 shop.amount %}</td>
          </tr>
        {% endfor %}
        
      </table>
      
      <table id="tab11">
      <tr class="tr4">
          <td class="td1"></td>
          <td class="td2">小計：</td>
          <td class="td3"></td>
          <td class="td4">NT${{ sub1 }}</td>
        </tr>
        <tr class="tr4">
          <td class="td1"></td>
          <td class="td2">運費：</td>
          <td class="td3"></td>
          <td class="td4">NT$60</td>
        </tr>
        <tr class="tr4">
          <td class="td1"></td>
          <td class="td2" id="td22" colspan="3"><hr></td>
        </tr>
        <tr class="tr4">
          <td class="td1"></td>
          <td class="td2">合計：</td>
          <td class="td3"></td>
          <td class="td4">NT${{ sub2 }}</td>
        </tr>
      </table>
      
      <br><br>
      
      <table id="tab2">
        <tr class="tr11"><td class="td11">收件人資料</td></tr>
        <tr class="tr12"><td class="td22">收件人名稱：{{ name }}</td></tr>
        <tr class="tr12"><td class="td22">收件人電話號碼：{{ phone }}</td></tr>
        <tr class="tr12"><td class="td22">地址：{{ address }}</td></tr>
        <form method="get" action="{% url 'shop:checkout' %}">
        <tr class="tr12"><td class="td22">送貨方式：
       {{ Delivery }}
        <input type="hidden" name="Delivery" value={{ Delivery }}>
        </td></tr>
        <tr class="tr12"><td class="td22" id="td0">付款方式：
        {{ payment }}
        <input type="hidden" name="payment" value={{ payment }}>
        </td></tr>
      </table>
      
      <table id="tab3">
        <tr class="tr11"><td class="td11">訂單備註</td></tr>
        <tr class="tr12">
        <td class="td22">
        <textarea name="remark">{{ remark }}</textarea>
        </td></tr>
      </table>
      
      <br><br>
      
       <table id="tab44">
          <tr>
            <td id="td1">
              <input class="btn" type="submit" value="返回結帳">
              </form>
            </td>
            <td id="td2">
            <form  method="post" action="{% url 'shop:fin' %}">
              {% csrf_token %}
              <input class="btn deleteConfirm" id="btn1" type="submit" value="確認提交">
            </form>
            </td>
          </tr>
       </table>
       
    </div>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src={% static 'main/js/deleteConfirm.js' %}></script>
  </body>
</html>

Web/shop/templates/shop/shop.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>購物車</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/shop.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    
    <div id="d4">
      <br>
      <img id="shop" src="{% static 'main/img/shop0.png' %}"  alt="shop">
      <br>
      <table id="tab1">
        <tr class="tr1">
          <td colspan="5">購物車</td>
        <tr>
        <tr class="tr2">
          <td>商品資料</td>
          <td>單件價格</td>
          <td>數量</td>
          <td></td>
          <td>小計</td>
        </tr>
        {% for shop in shops %}
          <tr class="tr3">
            <td>{{shop.name}}</td>
            <td>NT${{shop.price}}</td>
            <td>{{shop.amount}}</td>
            <td>
            <form  method="post" action="{% url 'shop:shopDelete' shop.id %}">
              {% csrf_token %}
              <input  type="submit" value="刪除">
            </form>
            </td>
            <td>NT${%  widthratio shop.price 1 shop.amount %}</td>
          </tr>
        {% endfor %}
      </table>
      <br><hr><br>
      
      <table id="tab2">
        <tr class="tr1">
          <td>送貨及付款方式</td>
        <tr>
        <tr class="tr2">
          <td>
          <p>送貨方式</p>
          <form method="get" action="{% url 'shop:checkout' %}">
            {% csrf_token %}
            <select id="Delivery" name="Delivery">
                    <option value="黑貓宅急便">黑貓宅急便</option>
                    <option value="中華郵政">中華郵政</option>
                    <option value="新竹貨運">新竹貨運</option>
            </select>
          <p>將貨物送往指定位址，運費統一60。</p>
          </td>
        </tr>
        <tr class="tr2">
            <td>
            <p>付款方式</p>
            <select id="payment" name="payment">
                    <option value="貨到付款">貨到付款</option>
                    <option value="轉帳">轉帳</option>
            </select>
            <br><br><br>
            </td>
        </tr>
      
      </table>
      
      <table id="tab3">
        <tr class="tr1">
          <td colspan="2">訂單資訊</td>
        <tr>
        <tr class="tr2">
          <td><p>小計</p></td>
          <td><p>NT${{ sub1 }}</p></td>
        </tr>
        <tr class="tr2">
            <td><p>運費</p></td>
            <td>
            {% if sub1 > 0 %}
              <p>NT$60</p>
            {% else %}
              <p>NT$0</p>
            {% endif %}
            </td>
        </tr>
        <tr class="tr2">
          <td colspan="2"><hr></td>
        <tr>
        <tr id="tr34" class="tr2">
            <td><p>合計</p></td>
            <td>
            {% if sub1 > 0 %}
              <p>NT${{ sub2 }}</p>
            {% else %}
              <p>NT$0</p>
            {% endif %}
            </td>
        </tr>
        <tr class="tr2">
            <td colspan="2">
            {% if sub1 > 0 %}
              <input class="btn" type="submit" value="前往結帳">
              </form>
            {% else %}
              <p>您購物車內沒有商品可以結帳</p>
            {% endif %}
            
            </td>
        </tr>
      </table>
      <br>
    </div>
   
  </body>
</html>